### ISSUE TITLE
Update README.md to Standard format

### ISSUE THREAD

**Issue by sbshah97** [Hrily/TicTacToe#1]
Include Instructions as to how to run the Android App!

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by josenildoamorim** [comment]
How do i claim? lol

**Comment by Hrily** [comment]
Just write `claim`

**Comment by josenildoamorim** [comment]
claim

**Comment by Hrily** [comment]
Okay work on it... :)
Just keep the download link blank, I'll update it soon...

**Comment by josenildoamorim** [comment]
done. hope its ok, first time i do it

**Comment by Hrily** [comment]
Merged the request... :+1: 
Good job...
