### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by sbshah97** [Hrily/TicTacToe#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by RiRam** [comment]
If this is available, I'm on it.

**Comment by Hrily** [comment]
Okay, work on it... :)

**Comment by RiRam** [comment]
Is there anything specific you would like to be included?

**Comment by Hrily** [comment]
For reference, check [here](https://github.com/salman-bhai/HandCricket/blob/master/CONTRIBUTING.MD)

**Comment by RiRam** [comment]
Opened pull request #5

**Comment by Hrily** [comment]
Merged pull request...
